import axios from 'axios';

//

// Employee
export const FETCH_EMPLOYEE_START = 'FETCH_EMPLOYEE_START';
export const FETCH_EMPLOYEE_SUCCESS = 'FETCH_EMPLOYEE_SUCCESS';
export const FETCH_EMPLOYEE_FAILURE = 'FETCH_EMPLOYEE_FAILURE';

// Jobsite
export const FETCH_JOBSITE_START = 'FETCH_JOBSITE_START';
export const FETCH_JOBSITE_SUCCESS = 'FETCH_JOBSITE_SUCCESS';
export const FETCH_JOBSITE_FAILURE = 'FETCH_JOBSITE_FAILURE';

// Building
export const FETCH_BUILDING_START = 'FETCH_BUILDING_START';
export const FETCH_BUILDING_SUCCESS = 'FETCH_BUILDING_SUCCESS';
export const FETCH_BUILDING_FAILURE = 'FETCH_BUILDING_FAILURE';

// Floor
export const FETCH_FLOOR_START = 'FETCH_FLOOR_START';
export const FETCH_FLOOR_SUCCESS = 'FETCH_FLOOR_SUCCESS';
export const FETCH_FLOOR_FAILURE = 'FETCH_FLOOR_FAILURE';

// Unit
export const FETCH_UNIT_START = 'FETCH_UNIT_START';
export const FETCH_UNIT_SUCCESS = 'FETCH_UNIT_SUCCESS';
export const FETCH_UNIT_FAILURE = 'FETCH_UNIT_FAILURE';
